/// Flutter icons Check_Manual
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Check_Manual
///      fonts:
///       - asset: fonts/Check_Manual.ttf
///
///
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Check_Manual {
  Check_Manual._();

  static const _kFontFam = 'Check_Manual';
  static const String? _kFontPkg = null;

  static const IconData check =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
