/// Flutter icons Download_Manual
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Download_Manual
///      fonts:
///       - asset: fonts/Download_Manual.ttf
///
///
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
///
import 'package:flutter/widgets.dart';

class Download_Manual {
  Download_Manual._();

  static const _kFontFam = 'Download_Manual';
  static const String? _kFontPkg = null;

  static const IconData download =
      IconData(0xe865, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
