/// Flutter icons StaggardBar_manual
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  StaggardBar_manual
///      fonts:
///       - asset: fonts/StaggardBar_manual.ttf
///
///
///
import 'package:flutter/widgets.dart';

class StaggardBar_manual {
  StaggardBar_manual._();

  static const _kFontFam = 'StaggardBar_manual';
  static const String? _kFontPkg = null;

  static const IconData bars_staggered_solid =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
